parameters:
    profiler_live.data_collector.request.class: Profiler\LiveBundle\Profiler\DataCollector\RequestDataCollector
    profiler_live.data_collector.memory.class: Profiler\LiveBundle\Profiler\DataCollector\MemoryDataCollector
    profiler_live.data_collector.timer.class: Profiler\LiveBundle\Profiler\DataCollector\TimerDataCollector
    profiler_live.data_collector.exception.class: Profiler\LiveBundle\Profiler\DataCollector\ExceptionDataCollector
    profiler_live.data_collector.doctrine.class: Profiler\LiveBundle\Profiler\DataCollector\DoctrineDataCollector
    profiler_live.swiftmailer.data_collector.class: Profiler\LiveBundle\Profiler\DataCollector\MessageDataCollector
